version: '3.8'

services:
  web:
    build: .
    image: bopobywek/web:latest
    env_file:
      - .env.dev
    expose:
      - 5000
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 80:80
      - 443:443
    depends_on:
      - web
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=soiree_admin
      - POSTGRES_PASSWORD=123abc
      - POSTGRES_DB=soiree

volumes:
  postgres_data:

