version: '3.8'

services:
  web:
    build: .
    env_file:
      - .env.dev
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: postgres:13-alpine
    environment:
      - POSTGRES_USER=soiree_admin
      - POSTGRES_PASSWORD=123abc
      - POSTGRES_DB=soiree

volumes:
  postgres_data:

